# Generated by Django 5.2 on 2026-05-24 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='abc_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='column_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mapping', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'column_mappings',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_edits', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='students.student')),
            ],
            options={
                'db_table': 'student_edit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', '-timestamp'], name='student_edi_student_48d478_idx')],
            },
        ),
    ]
